# base screenshot properties
[screenshot]
# display to take screenshot
display = "default"
# should contain cursor?
cursor = false
# should copy screenshot to clipborad?
clipboard = true
# should write screenshot as file in filesystem?
fs = true
# should write screenshot in stdout?
stdout = false

# properties related to writing screenshot as file in filesystem
[fs]
# output directory
path = "$HOME/images/screenshots"
# output filename format
format = "wayshot-%Y_%m_%d-%H_%M_%S"
# output file encoding
encoding = "png"
